# Generated by Django 5.2.10 on 2026-01-30 05:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=100)),
                ('branchLocation', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.CharField(editable=False, max_length=20, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('permanent_address', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=10)),
                ('pancard_no', models.CharField(max_length=50, unique=True)),
                ('aadharcard_no', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('active', 'inactive'), ('Unpaid', 'Unpaid')], default='active', max_length=10)),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='user_documents/pan/')),
                ('aadhar_image', models.ImageField(blank=True, null=True, upload_to='user_documents/aadhar/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('relationship', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='cheatfund.users')),
            ],
        ),
        migrations.CreateModel(
            name='ChitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.PositiveBigIntegerField(editable=False, null=True, unique=True)),
                ('ByLawsNumber', models.CharField(max_length=50)),
                ('BylawsDate', models.DateField()),
                ('GroupCode', models.CharField(max_length=50)),
                ('TicketNmber', models.CharField(max_length=50)),
                ('ChitValue', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('DurationCategory', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatfund.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatfund.users')),
            ],
        ),
        migrations.CreateModel(
            name='ChitAgreementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducts_of_chits', models.CharField(max_length=50)),
                ('number_of_tickets', models.CharField(max_length=10)),
                ('number_of_installments', models.IntegerField()),
                ('installment_amount', models.FloatField()),
                ('scheduled_auction_time', models.TimeField()),
                ('scheduled_auction_day', models.DateField()),
                ('scheduled_last_date_of_payment', models.DateField()),
                ('date_of_commencement', models.DateField()),
                ('date_of_termination', models.DateField()),
                ('first_auction_date', models.DateField()),
                ('auction_frequency', models.DateField()),
                ('auction_session_start', models.TimeField()),
                ('auction_session_end', models.TimeField()),
                ('register_bank_branch', models.CharField(max_length=200)),
                ('foreman_name', models.CharField(max_length=100)),
                ('company_reg_number', models.CharField(max_length=100)),
                ('deposit_bank_name', models.CharField(max_length=200)),
                ('deposit_receipt_no', models.CharField(max_length=200)),
                ('deposit_date', models.DateField()),
                ('term_month', models.CharField(max_length=10)),
                ('prize_collection', models.CharField(max_length=60)),
                ('jurisdiction_place', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatfund.branch')),
                ('chit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatfund.chitdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatfund.users')),
            ],
        ),
    ]
