# Generated by Django 5.2.5 on 2026-01-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheatFundUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mobile_no", models.CharField(max_length=15, unique=True)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("permanent_address", models.CharField(max_length=300)),
                ("pincode", models.CharField(max_length=10)),
                ("pancard_no", models.CharField(max_length=50, unique=True)),
                ("aadharcard_no", models.CharField(max_length=12, unique=True)),
                (
                    "pan_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_documents/pan/"
                    ),
                ),
                (
                    "aadhar_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_documents/aadhar/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nominee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mobile_no", models.CharField(max_length=15, unique=True)),
                ("dob", models.DateField()),
                ("relationship", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominees",
                        to="cheatfund.cheatfundusers",
                    ),
                ),
            ],
        ),
    ]
