# Generated by Django 5.2.5 on 2026-02-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="auth_user",
        ),
    ]
