# Generated by Django 5.2.5 on 2026-01-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CheatFundUsers",
            new_name="Users",
        ),
    ]
