# Generated by Django 5.2.5 on 2026-01-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0002_rename_cheatfundusers_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="name",
            new_name="firstname",
        ),
        migrations.RemoveField(
            model_name="nominee",
            name="name",
        ),
        migrations.AddField(
            model_name="nominee",
            name="firstname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="nominee",
            name="lastname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="nominee",
            name="middlename",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="lastname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="middlename",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
