# Generated by Django 5.2.5 on 2026-01-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0002_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="user",
        ),
    ]
