# Generated by Django 5.2.5 on 2026-02-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0002_remove_users_auth_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
    ]
