# Generated by Django 5.2.5 on 2026-01-19 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0003_remove_branch_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChitDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ByLawsNumber", models.CharField(max_length=50)),
                ("BylawsDate", models.DateField()),
                ("GroupCode", models.CharField(max_length=50)),
                ("TicketNmber", models.CharField(max_length=50)),
                ("ChitValue", models.IntegerField()),
                ("Duration", models.IntegerField()),
                ("DurationCategory", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cheatfund.branch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cheatfund.users",
                    ),
                ),
            ],
        ),
    ]
