# Generated by Django 5.2.5 on 2026-02-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0003_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
