# Generated by Django 5.2.5 on 2026-02-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0004_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitagreementdetails",
            name="date_of_commencement",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="chitagreementdetails",
            name="date_of_termination",
            field=models.DateField(null=True),
        ),
    ]
