# Generated by Django 5.2.5 on 2026-01-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0004_chitdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nominee",
            name="mobile_no",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="users",
            name="mobile_no",
            field=models.CharField(max_length=15),
        ),
    ]
