# Generated by Django 5.2.5 on 2026-01-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0005_alter_nominee_firstname_alter_nominee_lastname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
