# Generated by Django 5.2.5 on 2026-01-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0005_alter_nominee_mobile_no_alter_users_mobile_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="CustomerID",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
