# Generated by Django 5.2.5 on 2026-02-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0005_alter_chitagreementdetails_date_of_commencement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="aadhar_image_back",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_documents/aadhar/"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="pan_image_back",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_documents/pan/"
            ),
        ),
    ]
