# Generated by Django 5.2.5 on 2026-01-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0006_users_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="status",
            field=models.CharField(
                choices=[("active", "inactive"), ("Unpaid", "Unpaid")],
                default="active",
                max_length=10,
            ),
        ),
    ]
