# Generated by Django 5.2.5 on 2026-01-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0006_users_customerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitdetails",
            name="application_id",
            field=models.PositiveBigIntegerField(
                editable=False, null=True, unique=True
            ),
        ),
    ]
