# Generated by Django 5.2.5 on 2026-02-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0006_users_aadhar_image_back_users_pan_image_back"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
