# Generated by Django 5.2.5 on 2026-01-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0007_chitdetails_application_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChitAgreementDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conducts_of_chits", models.CharField(max_length=50)),
                ("number_of_tickent", models.CharField(max_length=10)),
                ("number_of_installments", models.IntegerField(max_length=50)),
                ("installment_amount", models.FloatField()),
                ("scheduled_auction_time", models.TimeField()),
                ("date_of_commencement", models.DateField()),
                ("date_of_termination", models.DateField()),
                ("first_auction_date", models.DateField()),
                ("auction_frequency", models.CharField(max_length=20)),
                ("auction_session_start", models.TimeField()),
                ("auction_session_end", models.TimeField()),
                ("register_bank_branch", models.CharField(max_length=200)),
                ("foreman_name", models.CharField(max_length=100)),
                ("company_reg_number", models.CharField(max_length=100)),
                ("deposit_bank_name", models.CharField(max_length=200)),
                ("deposit_receipt_no", models.CharField(max_length=200)),
                ("deposit_date", models.DateField()),
                ("term_month", models.CharField(max_length=10)),
                ("prize_collection_grace_days", models.CharField(max_length=60)),
                ("jurisdiction_place", models.CharField(max_length=50)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cheatfund.branch",
                    ),
                ),
                (
                    "chit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cheatfund.chitdetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cheatfund.users",
                    ),
                ),
            ],
        ),
    ]
