# Generated by Django 5.2.5 on 2026-03-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0007_alter_users_email"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE cheatfund_chitagreementdetails
            ALTER COLUMN scheduled_auction_day
            TYPE integer
            USING EXTRACT(DAY FROM scheduled_auction_day);
            """
        ),
    ]
