# Generated by Django 5.2.5 on 2026-03-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0008_alter_chitagreementdetails_scheduled_auction_day"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="chitagreementdetails",
        #     name="scheduled_auction_day",
        #     field=models.IntegerField(),
        # ),
        migrations.RunSQL(
            """
            ALTER TABLE cheatfund_chitagreementdetails
            ALTER COLUMN scheduled_last_date_of_payment
            TYPE integer
            USING EXTRACT(DAY FROM scheduled_last_date_of_payment);
            """
        ),
    ]
