# Generated by Django 5.2.5 on 2026-01-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0008_chitagreementdetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chitagreementdetails",
            old_name="number_of_tickent",
            new_name="number_of_tickets",
        ),
        migrations.AlterField(
            model_name="chitagreementdetails",
            name="number_of_installments",
            field=models.IntegerField(),
        ),
    ]
