# Generated by Django 5.2.5 on 2026-01-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cheatfund",
            "0009_rename_number_of_tickent_chitagreementdetails_number_of_tickets_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chitagreementdetails",
            name="scheduled_auction_day",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="chitagreementdetails",
            name="scheduled_last_date_of_payment",
            field=models.DateField(null=True),
        ),
    ]
