# Generated by Django 5.2.5 on 2026-03-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0009_alter_chitagreementdetails_scheduled_auction_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitagreementdetails",
            name="jurisdiction_place",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="chitagreementdetails",
            name="scheduled_auction_day",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="chitagreementdetails",
            name="scheduled_last_date_of_payment",
            field=models.IntegerField(),
        ),
    ]
