# Generated by Django 5.2.5 on 2026-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0010_chitagreementdetails_scheduled_auction_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitagreementdetails",
            name="auction_frequency",
            field=models.DateField(),
        ),
    ]
