# Generated by Django 5.2.5 on 2026-03-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0010_alter_chitagreementdetails_jurisdiction_place_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE cheatfund_chitagreementdetails
            ALTER COLUMN auction_frequency
            TYPE integer
            USING EXTRACT(DAY FROM auction_frequency);
            """
        ),
    ]
