# Generated by Django 5.2.5 on 2026-03-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0011_alter_chitagreementdetails_auction_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitagreementdetails",
            name="auction_frequency",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="Gurantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("middlename", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("pancard_no", models.CharField(max_length=50, unique=True)),
                ("aadharcard_no", models.CharField(max_length=12, unique=True)),
                (
                    "pan_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_documents/pan/"
                    ),
                ),
                (
                    "aadhar_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_documents/aadhar/"
                    ),
                ),
                (
                    "aadhar_image_back",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_documents/aadhar/"
                    ),
                ),
                ("dob", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cheatfund.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BidAgreementDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateofAuction", models.DateField()),
                ("totalBidAmount", models.CharField(max_length=100)),
                ("auctionNumber", models.CharField(max_length=50)),
                ("prizedAmount", models.CharField(max_length=50, null=True)),
                ("dividend", models.IntegerField()),
                ("totalMemberofGroup", models.IntegerField()),
                ("suretyReceived", models.CharField(max_length=100)),
                ("suretiesVerified", models.CharField(max_length=100)),
                ("dateOfPayment", models.DateField()),
                ("chequeNo", models.CharField(max_length=100)),
                ("cheqDate", models.DateField()),
                ("cheqBank", models.CharField(max_length=200)),
                ("foremanCommision", models.CharField(max_length=100)),
                ("debitBankName", models.CharField(verbose_name=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chitAgreementDetails",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cheatfund.chitagreementdetails",
                    ),
                ),
                (
                    "gurantor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cheatfund.gurantor",
                    ),
                ),
            ],
        ),
    ]
