# Generated by Django 5.2.5 on 2026-01-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0011_alter_chitagreementdetails_auction_frequency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chitagreementdetails",
            old_name="prize_collection_grace_days",
            new_name="prize_collection",
        ),
    ]
