# Generated by Django 5.2.5 on 2026-03-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0012_alter_chitagreementdetails_auction_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidagreementdetails",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cheatfund.users",
            ),
        ),
        migrations.AddField(
            model_name="gurantor",
            name="mobile_no",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
