# Generated by Django 5.2.5 on 2026-01-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cheatfund",
            "0012_rename_prize_collection_grace_days_chitagreementdetails_prize_collection",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chitagreementdetails",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="chitagreementdetails",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
