# Generated by Django 5.2.5 on 2026-03-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0013_bidagreementdetails_user_gurantor_mobile_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bidagreementdetails",
            old_name="chitAgreementDetails",
            new_name="chitAgreement",
        ),
    ]
