# Generated by Django 5.2.5 on 2026-03-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cheatfund",
            "0014_rename_chitagreementdetails_bidagreementdetails_chitagreement",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidagreementdetails",
            name="gurantor",
        ),
        migrations.AddField(
            model_name="bidagreementdetails",
            name="gurantor",
            field=models.ManyToManyField(to="cheatfund.gurantor"),
        ),
    ]
