# Generated by Django 5.2.5 on 2026-03-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0015_remove_bidagreementdetails_gurantor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidagreementdetails",
            name="suretyReceived",
            field=models.DateField(),
        ),
    ]
