# Generated by Django 5.2.5 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0015_remove_bidagreementdetails_gurantor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="pan_image_back",
        ),
        migrations.AlterField(
            model_name="bidagreementdetails",
            name="suretiesVerified",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
