# Generated by Django 5.2.5 on 2026-03-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0016_remove_users_pan_image_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitagreementdetails",
            name="scheduled_last_date_of_payment",
            field=models.IntegerField(null=True),
        ),
    ]
