# Generated by Django 5.2.5 on 2026-03-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0016_alter_bidagreementdetails_suretyreceived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidagreementdetails",
            name="suretyReceived",
            field=models.CharField(max_length=100),
        ),
    ]
