# Generated by Django 5.2.5 on 2026-03-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0017_alter_bidagreementdetails_suretyreceived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidagreementdetails",
            name="suretiesVerified",
        ),
    ]
