# Generated by Django 5.2.5 on 2026-03-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0017_alter_chitagreementdetails_scheduled_last_date_of_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitagreementdetails",
            name="prize_collection",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
