# Generated by Django 5.2.5 on 2026-03-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0018_remove_bidagreementdetails_suretiesverified"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidagreementdetails",
            name="suretiesVerified",
            field=models.DateField(null=True),
        ),
    ]
