# Generated by Django 5.2.5 on 2026-03-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheatfund", "0018_alter_chitagreementdetails_prize_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidagreementdetails",
            name="cheqBank",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="bidagreementdetails",
            name="cheqDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="bidagreementdetails",
            name="chequeNo",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
